## Importing important libraries

In [1]:
import pandas as pd

## Reading stack exchange data acquired in pandas dataframe

In [2]:
df=pd.read_csv("C:/Users/Haresh/Desktop/Assignments/Cloud Technology/csv/QueryResults (1).csv")

In [3]:
df1=pd.read_csv("C:/Users/Haresh/Desktop/Assignments/Cloud Technology/csv/QueryResults (2).csv")

In [4]:
df2=pd.read_csv("C:/Users/Haresh/Desktop/Assignments/Cloud Technology/csv/QueryResults (3).csv")

In [5]:
df3=pd.read_csv("C:/Users/Haresh/Desktop/Assignments/Cloud Technology/csv/QueryResults (4).csv")

In [6]:
df.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,927358,1,927386.0,NaN,2009-05-29 18:09:14,NaN,23303,10030841,<p>I accidentally <strong>committed the wrong ...,89904.0,...,2021-06-30 05:07:30,2021-10-05 13:26:47,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,9,7309.0,NaN,2013-03-16 10:08:31,CC BY-SA 4.0
1,2003505,1,2003515.0,NaN,2010-01-05 01:12:15,NaN,18475,9258686,<p>I want to delete a branch both locally and ...,95592.0,...,2021-10-06 22:38:35,2021-10-06 22:38:35,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5718.0,NaN,NaN,CC BY-SA 4.0
2,5767325,1,5767357.0,NaN,2011-04-23 22:17:18,NaN,9899,8897394,<p>I have an array of numbers and I'm using th...,364969.0,...,2020-05-21 04:20:03,2021-09-24 08:51:22,How can I remove a specific item from an array?,<javascript><arrays>,112,4,1501.0,NaN,NaN,CC BY-SA 4.0
3,16956810,1,16957078.0,NaN,2013-06-06 08:06:45,NaN,6286,8203000,<p>I'm trying to find a way to scan my entire ...,954986.0,...,2017-05-21 11:40:16,2021-08-30 13:56:02,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3029.0,NaN,NaN,CC BY-SA 3.0
4,2906582,1,2906586.0,NaN,2010-05-25 16:39:47,NaN,2298,7782563,<p>I would like to create an HTML button that ...,48523.0,...,2021-04-21 16:46:06,2021-09-22 19:42:43,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN,CC BY-SA 4.0

In [7]:
df1.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,47772157,1,47793764.0,NaN,2017-12-12 12:01:59,NaN,50,127400,<p>I'm on a windows machine without admin righ...,2344958.0,...,2020-02-25 03:26:17,2021-10-08 13:46:46,How to change the default browser used by jupy...,<windows><google-chrome><anaconda><jupyter>,23,0,24.0,NaN,NaN,CC BY-SA 4.0
1,37306672,1,NaN,NaN,2016-05-18 17:39:46,NaN,97,127397,<p>Just installed Visual Studio Code 1.1.1 on ...,1864541.0,...,2018-07-24 13:36:38,2021-08-17 09:51:40,"Visual Studio Code ""Open With Code"" does not a...",<windows-7><visual-studio-code><windows-7-x64>,21,1,13.0,NaN,NaN,CC BY-SA 3.0
2,22700728,1,41141129.0,NaN,2014-03-27 22:39:46,NaN,78,127395,<p>i ran in a problem using composer for insta...,1315408.0,...,2019-09-24 17:27:51,2021-01-15 08:53:03,Composer loading from cache,<php><composer-php>,9,2,11.0,NaN,NaN,CC BY-SA 3.0
3,70272,1,70296.0,NaN,2008-09-16 08:10:53,NaN,77,127392,"<p>I have an application with one form in it, ...",1500.0,...,2013-11-03 16:14:38,2019-06-21 06:49:01,Single Form Hide on Startup,<c#><vb.net><winforms>,23,0,29.0,NaN,NaN,CC BY-SA 3.0
4,2643462,1,2643598.0,NaN,2010-04-15 07:39:40,NaN,23,127391,<p>I'm trying to access a Active Directory fro...,286295.0,...,NaN,2017-07-27 15:12:33,Setting up SSL on a local xampp/apache server,<php><apache><ssl><https><xampp>,6,1,8.0,NaN,NaN,CC BY-SA 2.5

In [8]:
df2.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,15895266,1,NaN,NaN,2013-04-09 06:56:00,NaN,12,74594,<p>I am using PHPEXxcel to export an HTML Tabl...,2143432.0,...,2016-12-19 06:50:23,2018-07-11 08:52:56,Using PHPExcel to export to xlsx,<php><phpexcel>,4,2,6.0,NaN,NaN,CC BY-SA 3.0
1,6974231,1,52629824.0,NaN,2011-08-07 16:53:48,NaN,129,74594,"<p>So, I'm <em>TRYING</em> to release some sof...",46616.0,...,2011-08-07 16:56:14,2020-05-28 09:01:24,proguard hell - can't find referenced class,<android><proguard>,9,5,19.0,NaN,NaN,CC BY-SA 3.0
2,13454699,1,13455078.0,NaN,2012-11-19 13:22:45,NaN,30,74594,<p>I created MVC Application that have 3 diffe...,1437422.0,...,2013-08-18 00:22:07,2017-10-27 23:52:29,How to register areas for routing,<c#><asp.net><asp.net-mvc><asp.net-mvc-4>,3,8,9.0,NaN,NaN,CC BY-SA 3.0
3,1806585,1,1806597.0,NaN,2009-11-27 03:16:22,NaN,229,74592,<p>I read that Linux is a monolithic kernel. D...,207335.0,...,2011-09-20 06:19:40,2019-03-18 16:27:03,Why is Linux called a monolithic kernel?,<architecture><operating-system><linux-kernel>,6,0,129.0,NaN,NaN,CC BY-SA 3.0
4,2950971,1,2951046.0,NaN,2010-06-01 15:18:31,NaN,62,74591,<p>I have a Python script that I'd like to com...,148765.0,...,2020-06-20 04:40:01,2021-10-04 22:06:59,Packaging a Python script on Linux into a Wind...,<python><linux><windows><py2exe>,6,5,24.0,NaN,NaN,CC BY-SA 4.0

In [9]:
df3.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,1616822,1,1616825.0,NaN,2009-10-24 03:15:53,NaN,3,53209,"<p>Why <code>&lt;div style=""width:50%"" /&gt;</...",90096.0,...,2009-10-24 03:21:19,2009-10-24 12:22:19,"Why <div style=""width:50%"" /> is not rendered ...",<css><xhtml-1.0-strict><xhtml>,3,2,NaN,NaN,NaN,CC BY-SA 2.5
1,23667528,1,NaN,NaN,2014-05-15 00:52:26,NaN,25,53209,<p>Why doesn't <code>:not(:last-of-type)</code...,NaN,...,2014-05-15 01:07:59,2014-05-15 01:27:10,:not(:last-of-type) not working for class,<css><css-selectors>,2,4,2.0,NaN,NaN,CC BY-SA 3.0
2,12486488,1,12486522.0,NaN,2012-09-18 23:23:42,NaN,3,53209,<p>I'd like to change the color of my navbar f...,1379955.0,...,NaN,2015-10-28 13:27:55,Change background color in navbar fixed menu b...,<twitter-bootstrap>,2,1,3.0,NaN,NaN,CC BY-SA 3.0
3,5606747,1,5606776.0,NaN,2011-04-09 17:50:07,NaN,14,53209,<p>i am using </p>\n\n<p><code>string path = A...,NaN,...,NaN,2019-03-13 09:20:53,How to get application path,<c#><c#-4.0><c#-2.0>,7,3,3.0,NaN,NaN,CC BY-SA 3.0
4,5279079,1,5533882.0,NaN,2011-03-11 22:31:43,NaN,18,53209,<p>This is my query:</p>\n\n<pre><code>SELECT ...,656079.0,...,2011-03-11 22:44:00,2019-08-20 17:21:50,"MySQL convert timediff output to day, hour, mi...",<mysql>,5,1,8.0,NaN,NaN,CC BY-SA 2.5

In [10]:
col_list = list(df)
print (col_list)

['Id', 'PostTypeId', 'AcceptedAnswerId', 'ParentId', 'CreationDate', 'DeletionDate', 'Score', 'ViewCount', 'Body', 'OwnerUserId', 'OwnerDisplayName', 'LastEditorUserId', 'LastEditorDisplayName', 'LastEditDate', 'LastActivityDate', 'Title', 'Tags', 'AnswerCount', 'CommentCount', 'FavoriteCount', 'ClosedDate', 'CommunityOwnedDate', 'ContentLicense']

In [11]:
df.isnull().sum()

Id                           0
PostTypeId                   0
AcceptedAnswerId          7742
ParentId                 50000
CreationDate                 0
DeletionDate             50000
Score                        0
ViewCount                    0
Body                         0
OwnerUserId               1434
OwnerDisplayName         44712
LastEditorUserId          6742
LastEditorDisplayName    46663
LastEditDate              6194
LastActivityDate             0
Title                        0
Tags                         0
AnswerCount                  0
CommentCount                 0
FavoriteCount               91
ClosedDate               45344
CommunityOwnedDate       49523
ContentLicense               0
dtype: int64

# Data Cleaning

### Importing beautifulsoup for working on html tags

In [12]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\haresh\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\haresh\anaconda3\lib\site-packages (from beautifulsoup4) (2.2.1)

In [13]:
from bs4 import BeautifulSoup

### Creating function rm_tags to remove html tags from the data

In [14]:
def rm_tags(raw_html):
   clean=BeautifulSoup(raw_html, "lxml").text
   return clean

In [15]:
df["Body"]=df["Body"].apply(rm_tags)

In [16]:
df1["Body"]=df1["Body"].apply(rm_tags)

In [17]:
df2["Body"]=df2["Body"].apply(rm_tags)

In [18]:
df3["Body"]=df3["Body"].apply(rm_tags)

In [19]:
df.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,927358,1,927386.0,NaN,2009-05-29 18:09:14,NaN,23303,10030841,I accidentally committed the wrong files to Gi...,89904.0,...,2021-06-30 05:07:30,2021-10-05 13:26:47,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,9,7309.0,NaN,2013-03-16 10:08:31,CC BY-SA 4.0
1,2003505,1,2003515.0,NaN,2010-01-05 01:12:15,NaN,18475,9258686,I want to delete a branch both locally and rem...,95592.0,...,2021-10-06 22:38:35,2021-10-06 22:38:35,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5718.0,NaN,NaN,CC BY-SA 4.0
2,5767325,1,5767357.0,NaN,2011-04-23 22:17:18,NaN,9899,8897394,I have an array of numbers and I'm using the ....,364969.0,...,2020-05-21 04:20:03,2021-09-24 08:51:22,How can I remove a specific item from an array?,<javascript><arrays>,112,4,1501.0,NaN,NaN,CC BY-SA 4.0
3,16956810,1,16957078.0,NaN,2013-06-06 08:06:45,NaN,6286,8203000,I'm trying to find a way to scan my entire Lin...,954986.0,...,2017-05-21 11:40:16,2021-08-30 13:56:02,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3029.0,NaN,NaN,CC BY-SA 3.0
4,2906582,1,2906586.0,NaN,2010-05-25 16:39:47,NaN,2298,7782563,I would like to create an HTML button that act...,48523.0,...,2021-04-21 16:46:06,2021-09-22 19:42:43,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN,CC BY-SA 4.0

In [20]:
df1.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,47772157,1,47793764.0,NaN,2017-12-12 12:01:59,NaN,50,127400,I'm on a windows machine without admin right a...,2344958.0,...,2020-02-25 03:26:17,2021-10-08 13:46:46,How to change the default browser used by jupy...,<windows><google-chrome><anaconda><jupyter>,23,0,24.0,NaN,NaN,CC BY-SA 4.0
1,37306672,1,NaN,NaN,2016-05-18 17:39:46,NaN,97,127397,Just installed Visual Studio Code 1.1.1 on a W...,1864541.0,...,2018-07-24 13:36:38,2021-08-17 09:51:40,"Visual Studio Code ""Open With Code"" does not a...",<windows-7><visual-studio-code><windows-7-x64>,21,1,13.0,NaN,NaN,CC BY-SA 3.0
2,22700728,1,41141129.0,NaN,2014-03-27 22:39:46,NaN,78,127395,i ran in a problem using composer for installi...,1315408.0,...,2019-09-24 17:27:51,2021-01-15 08:53:03,Composer loading from cache,<php><composer-php>,9,2,11.0,NaN,NaN,CC BY-SA 3.0
3,70272,1,70296.0,NaN,2008-09-16 08:10:53,NaN,77,127392,"I have an application with one form in it, and...",1500.0,...,2013-11-03 16:14:38,2019-06-21 06:49:01,Single Form Hide on Startup,<c#><vb.net><winforms>,23,0,29.0,NaN,NaN,CC BY-SA 3.0
4,2643462,1,2643598.0,NaN,2010-04-15 07:39:40,NaN,23,127391,I'm trying to access a Active Directory from m...,286295.0,...,NaN,2017-07-27 15:12:33,Setting up SSL on a local xampp/apache server,<php><apache><ssl><https><xampp>,6,1,8.0,NaN,NaN,CC BY-SA 2.5

In [21]:
df2.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,15895266,1,NaN,NaN,2013-04-09 06:56:00,NaN,12,74594,I am using PHPEXxcel to export an HTML Table g...,2143432.0,...,2016-12-19 06:50:23,2018-07-11 08:52:56,Using PHPExcel to export to xlsx,<php><phpexcel>,4,2,6.0,NaN,NaN,CC BY-SA 3.0
1,6974231,1,52629824.0,NaN,2011-08-07 16:53:48,NaN,129,74594,"So, I'm TRYING to release some software but Pr...",46616.0,...,2011-08-07 16:56:14,2020-05-28 09:01:24,proguard hell - can't find referenced class,<android><proguard>,9,5,19.0,NaN,NaN,CC BY-SA 3.0
2,13454699,1,13455078.0,NaN,2012-11-19 13:22:45,NaN,30,74594,I created MVC Application that have 3 differen...,1437422.0,...,2013-08-18 00:22:07,2017-10-27 23:52:29,How to register areas for routing,<c#><asp.net><asp.net-mvc><asp.net-mvc-4>,3,8,9.0,NaN,NaN,CC BY-SA 3.0
3,1806585,1,1806597.0,NaN,2009-11-27 03:16:22,NaN,229,74592,I read that Linux is a monolithic kernel. Does...,207335.0,...,2011-09-20 06:19:40,2019-03-18 16:27:03,Why is Linux called a monolithic kernel?,<architecture><operating-system><linux-kernel>,6,0,129.0,NaN,NaN,CC BY-SA 3.0
4,2950971,1,2951046.0,NaN,2010-06-01 15:18:31,NaN,62,74591,I have a Python script that I'd like to compil...,148765.0,...,2020-06-20 04:40:01,2021-10-04 22:06:59,Packaging a Python script on Linux into a Wind...,<python><linux><windows><py2exe>,6,5,24.0,NaN,NaN,CC BY-SA 4.0

In [22]:
df3.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,1616822,1,1616825.0,NaN,2009-10-24 03:15:53,NaN,3,53209,"Why <div style=""width:50%"" /> is not rendered ...",90096.0,...,2009-10-24 03:21:19,2009-10-24 12:22:19,"Why <div style=""width:50%"" /> is not rendered ...",<css><xhtml-1.0-strict><xhtml>,3,2,NaN,NaN,NaN,CC BY-SA 2.5
1,23667528,1,NaN,NaN,2014-05-15 00:52:26,NaN,25,53209,Why doesn't :not(:last-of-type) work in the fo...,NaN,...,2014-05-15 01:07:59,2014-05-15 01:27:10,:not(:last-of-type) not working for class,<css><css-selectors>,2,4,2.0,NaN,NaN,CC BY-SA 3.0
2,12486488,1,12486522.0,NaN,2012-09-18 23:23:42,NaN,3,53209,I'd like to change the color of my navbar fixe...,1379955.0,...,NaN,2015-10-28 13:27:55,Change background color in navbar fixed menu b...,<twitter-bootstrap>,2,1,3.0,NaN,NaN,CC BY-SA 3.0
3,5606747,1,5606776.0,NaN,2011-04-09 17:50:07,NaN,14,53209,i am using \nstring path = AppDomain.CurrentDo...,NaN,...,NaN,2019-03-13 09:20:53,How to get application path,<c#><c#-4.0><c#-2.0>,7,3,3.0,NaN,NaN,CC BY-SA 3.0
4,5279079,1,5533882.0,NaN,2011-03-11 22:31:43,NaN,18,53209,"This is my query:\nSELECT TIMEDIFF(end_time,st...",656079.0,...,2011-03-11 22:44:00,2019-08-20 17:21:50,"MySQL convert timediff output to day, hour, mi...",<mysql>,5,1,8.0,NaN,NaN,CC BY-SA 2.5

### Importing Regular expression module

In [23]:
import re
import string

### Defining function rm_punc to remove punctuations from the data

In [24]:
def rm_punc(word):
   pattern = r'[' + string.punctuation + ']'
   return re.sub(pattern, '', word)

In [25]:
df["Body"]=df["Body"].apply(rm_punc)

In [26]:
df1["Body"]=df1["Body"].apply(rm_punc)
df2["Body"]=df2["Body"].apply(rm_punc)
df3["Body"]=df3["Body"].apply(rm_punc)

In [27]:
df["Title"]=df["Title"].apply(rm_punc)

In [28]:
df1["Title"]=df1["Title"].apply(rm_punc)
df2["Title"]=df2["Title"].apply(rm_punc)
df3["Title"]=df3["Title"].apply(rm_punc)

In [29]:
df.head()

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense
0,927358,1,927386.0,NaN,2009-05-29 18:09:14,NaN,23303,10030841,I accidentally committed the wrong files to Gi...,89904.0,...,2021-06-30 05:07:30,2021-10-05 13:26:47,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,9,7309.0,NaN,2013-03-16 10:08:31,CC BY-SA 4.0
1,2003505,1,2003515.0,NaN,2010-01-05 01:12:15,NaN,18475,9258686,I want to delete a branch both locally and rem...,95592.0,...,2021-10-06 22:38:35,2021-10-06 22:38:35,How do I delete a Git branch locally and remotely,<git><version-control><git-branch><git-push><g...,41,10,5718.0,NaN,NaN,CC BY-SA 4.0
2,5767325,1,5767357.0,NaN,2011-04-23 22:17:18,NaN,9899,8897394,I have an array of numbers and Im using the pu...,364969.0,...,2020-05-21 04:20:03,2021-09-24 08:51:22,How can I remove a specific item from an array,<javascript><arrays>,112,4,1501.0,NaN,NaN,CC BY-SA 4.0
3,16956810,1,16957078.0,NaN,2013-06-06 08:06:45,NaN,6286,8203000,Im trying to find a way to scan my entire Linu...,954986.0,...,2017-05-21 11:40:16,2021-08-30 13:56:02,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3029.0,NaN,NaN,CC BY-SA 3.0
4,2906582,1,2906586.0,NaN,2010-05-25 16:39:47,NaN,2298,7782563,I would like to create an HTML button that act...,48523.0,...,2021-04-21 16:46:06,2021-09-22 19:42:43,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN,CC BY-SA 4.0

### Replacing \n new line, \t tab, \r carriagereturn, \b backspace, \f form feed

In [30]:
df = df.replace(r'\n',' ', regex=True)
df = df.replace(r'\t',' ', regex=True)
df = df.replace(r'\r',' ', regex=True)
df = df.replace(r'\b',' ', regex=True)
df = df.replace(r'\f',' ', regex=True)

In [31]:
df1 = df1.replace(r'\n',' ', regex=True)
df1 = df1.replace(r'\t',' ', regex=True)
df1 = df1.replace(r'\r',' ', regex=True)
df1 = df1.replace(r'\b',' ', regex=True)
df1 = df1.replace(r'\f',' ', regex=True)

In [32]:
df2 = df2.replace(r'\n',' ', regex=True)
df2 = df2.replace(r'\t',' ', regex=True)
df2 = df2.replace(r'\r',' ', regex=True)
df2 = df2.replace(r'\b',' ', regex=True)
df2 = df2.replace(r'\f',' ', regex=True)

In [33]:
df3 = df3.replace(r'\n',' ', regex=True)
df3 = df3.replace(r'\t',' ', regex=True)
df3 = df3.replace(r'\r',' ', regex=True)
df3 = df3.replace(r'\b',' ', regex=True)
df3 = df3.replace(r'\f',' ', regex=True)

## Downloading clean data as csv file

In [34]:
df.to_csv("clean_data_csv.csv")
df1.to_csv("clean_data_csv1.csv")
df2.to_csv("clean_data_csv2.csv")
df3.to_csv("clean_data_csv3.csv")

## Downloading clean data as text file

In [35]:
df.to_csv("clean_data.txt")
df1.to_csv("clean_data1.txt")
df2.to_csv("clean_data2.txt")
df3.to_csv("clean_data3.txt")